package com.parser;

// Generated Feb 11, 2013 12:34:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PreUserDetails generated by hbm2java
 */
public class PreUserDetails implements java.io.Serializable {

	
	private PreUserDetails preUserDetails;	
	private String userName;
	private String userEmail;
	private String userPassword;
	private String mobNo;
	private String desingation;
	private char isActive;
        private String rmManager;
        private String emailNotification;
	
	public PreUserDetails() {
        }

	

	

	

	
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getMobNo() {
		return this.mobNo;
	}

	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}

	public String getDesingation() {
		return this.desingation;
	}

	public void setDesingation(String desingation) {
		this.desingation = desingation;
	}

	public char getIsActive() {
		return this.isActive;
	}

	public void setIsActive(char isActive) {
		this.isActive = isActive;
	}

	public String getEmailNotification() {
		return this.emailNotification;
	}

	public void setEmailNotification(String emailNotification) {
		this.emailNotification = emailNotification;
	}

    /**
     * @return the rmManager
     */
    public String getRmManager() {
        return rmManager;
    }

    /**
     * @param rmManager the rmManager to set
     */
    public void setRmManager(String rmManager) {
        this.rmManager = rmManager;
    }

   

	

	
}
