/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.msr.reportstab;

import com.msr.reportsdao.BankTransactionBean;

import com.msr.util.SingletonClass;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author piyush chawla
 * @since march 08, 2013
 * @version V1.0
 * 
 */
public class BankTransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form BankTransactionPanel
     */
    
    List<BankTransactionBean> bankTxList = null;
    public BankTransactionPanel(String email , List<BankTransactionBean> bankTxList) {
       this.bankTxList= bankTxList;
        System.out.println("meeting list size is"+bankTxList.size());
        initComponents();
        int counter = 0;
        DefaultTableModel tableModel = (DefaultTableModel) bankTable.getModel();
        Iterator<BankTransactionBean> itr = bankTxList.iterator();
        while(itr.hasNext()){
         BankTransactionBean  rmTxBean = itr.next();
          tableModel.insertRow(counter, new Object[]{});
        bankTable.setValueAt(counter+1, counter, 0);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getTxnStatus()), counter, 1);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getTxnType()), counter, 2);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getClientName()), counter, 3);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getRmName()), counter, 4);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getActualLimit()), counter, 5);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getProposedLimit()), counter, 6);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getLimitType()), counter, 7);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getLimitInitiated()), counter, 8);
        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getLimitCompleted()), counter, 9);
//        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getLimitType()), counter, 10);
//        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getProposedLimit()), counter, 11);
//        bankTable.setValueAt(SingletonClass.replaceEmptySpace(rmTxBean.getActualLimit()), counter, 12);
        counter++;
        }
      TableColumn col0 = bankTable.getColumnModel().getColumn(0);
       col0.setWidth(60);
       col0.setMaxWidth(60);
//       col0.setResizable(false);
        TableColumn col1 = bankTable.getColumnModel().getColumn(1);
       col1.setMinWidth(200);
       col1.setWidth(200);
       col1.setMaxWidth(200);
//       col1.setResizable(false);
       TableColumn col2 = bankTable.getColumnModel().getColumn(2);
       col2.setMinWidth(200);
       col2.setWidth(200);
       col2.setMaxWidth(200);
//       col2.setResizable(false);
       TableColumn col3 = bankTable.getColumnModel().getColumn(3);
       col3.setMinWidth(200);
       col3.setWidth(200);
       col3.setMaxWidth(200);
//       col3.setResizable(false);
        TableColumn col4 = bankTable.getColumnModel().getColumn(4);
       col4.setMinWidth(200);
       col4.setWidth(200);
       col4.setMaxWidth(200);
//       col4.setResizable(false);
       TableColumn col5 = bankTable.getColumnModel().getColumn(5);
       col5.setMinWidth(200);
       col5.setWidth(200);
       col5.setMaxWidth(200);
//       col5.setResizable(false);
       TableColumn col6 = bankTable.getColumnModel().getColumn(6);
       col6.setMinWidth(200);
       col6.setWidth(200);
       col6.setMaxWidth(200);
//       col6.setResizable(false);
       TableColumn col7 = bankTable.getColumnModel().getColumn(7);
       col7.setMinWidth(200);
       col7.setWidth(200);
       col7.setMaxWidth(200);
//       col7.setResizable(false);
       TableColumn col8 = bankTable.getColumnModel().getColumn(8);
       col8.setMinWidth(200);
       col8.setWidth(200);
       col8.setMaxWidth(200);
//       col8.setResizable(false);
       TableColumn col9 = bankTable.getColumnModel().getColumn(9);
       col9.setMinWidth(200);
       col9.setWidth(200);
       col9.setMaxWidth(200);
//       col9.setResizable(false);
        
//      Limit", "Initiated On", "Completed On"
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();

        JTableHeader header = bankTable.getTableHeader();
        header.setBackground(new Color(192, 191, 200));
        //header.setPreferredSize(new Dimension(600,35));
        Font font = new Font("Serif", Font.BOLD, 14);
        header.setForeground(new Color(0, 103, 204));

        header.setFont(font);
        bankTable.setRowHeight(35);
        bankTable.setAutoCreateRowSorter(true);
        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.","Status", "Nature of Transaction","Client Name","RM","Sanction Limit", "Proposed Limit","Type Of Limit", "Initiated On", "Completed On"
            }
        ));
        bankTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(bankTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bankTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
