/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.msr.reportstab;

import com.msr.reportsdao.HistoryBean;
import com.msr.reportsdao.QueryDetailBean;
import com.msr.util.SingletonClass;
import java.awt.Color;
import java.awt.Font;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author root
 */
public class HistoryReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryReportPanel
     */
    List<HistoryBean> historyList = null;
    private String email = null;
    public HistoryReportPanel(String email , List<HistoryBean> historyList) {
        this.historyList = historyList;
        this.email = email;
        initComponents();
        int counter = 0;
        DefaultTableModel tableModel = (DefaultTableModel) historyTable.getModel();
        Iterator<HistoryBean> itr = historyList.iterator();
        while(itr.hasNext()){
            HistoryBean  historyBean = itr.next();
          tableModel.insertRow(counter, new Object[]{});
          
//        "Tx.No.","Status","Transaction Type","Client Name","Bank Name","Beneficiary","Limit Sanctioned","Sanctioned Date","Available Limit"
          
        historyTable.setValueAt(historyBean.getTxNo(), counter, 0);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getTxStatus()), counter, 1);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getTxType()), counter, 2);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getClientName()), counter, 3);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getBankName()), counter, 4);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getBeneficiary()), counter, 5);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getLimitSanctioned()), counter, 6);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getSantionDate()), counter, 7);
        historyTable.setValueAt(SingletonClass.replaceEmptySpace(historyBean.getAvailableLimit()), counter, 8);
        counter++;
        }
        
       TableColumn col0 = historyTable.getColumnModel().getColumn(0);
       col0.setWidth(60);
       col0.setMaxWidth(60);
//       col0.setResizable(false);
        TableColumn col1 = historyTable.getColumnModel().getColumn(1);
       col1.setMinWidth(200);
       col1.setWidth(200);
       col1.setMaxWidth(200);
//       col1.setResizable(false);
       TableColumn col2 = historyTable.getColumnModel().getColumn(2);
       col2.setMinWidth(200);
       col2.setWidth(200);
       col2.setMaxWidth(200);
//       col2.setResizable(false);
       TableColumn col3 = historyTable.getColumnModel().getColumn(3);
       col3.setMinWidth(200);
       col3.setWidth(200);
       col3.setMaxWidth(200);
//       col3.setResizable(false);
        TableColumn col4 = historyTable.getColumnModel().getColumn(4);
       col4.setMinWidth(200);
       col4.setWidth(200);
       col4.setMaxWidth(200);
//       col4.setResizable(false);
       TableColumn col5 = historyTable.getColumnModel().getColumn(5);
       col5.setMinWidth(200);
       col5.setWidth(200);
       col5.setMaxWidth(200);
//       col5.setResizable(false);
       TableColumn col6 = historyTable.getColumnModel().getColumn(6);
       col6.setMinWidth(200);
       col6.setWidth(200);
       col6.setMaxWidth(200);
//       col6.setResizable(false);
       TableColumn col7 = historyTable.getColumnModel().getColumn(7);
       col7.setMinWidth(200);
       col7.setWidth(200);
       col7.setMaxWidth(200);
//       col7.setResizable(false);
       TableColumn col8 = historyTable.getColumnModel().getColumn(8);
       col8.setMinWidth(200);
       col8.setWidth(200);
       col8.setMaxWidth(200);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        JTableHeader header = historyTable.getTableHeader();
        header.setBackground(new Color(192, 191, 200));
        //header.setPreferredSize(new Dimension(600,35));
        Font font = new Font("Serif", Font.BOLD, 14);
        header.setForeground(new Color(0, 103, 204));

        header.setFont(font);
        historyTable.setRowHeight(35);
        historyTable.setAutoCreateRowSorter(true);
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tx.No.","Status","Transaction Type","Client Name","Bank Name","Beneficiary","Limit Sanctioned","Sanctioned Date","Available Limit"
            }
        ));
        historyTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(historyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historyTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
