/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.msr.reportstab;

import com.msr.reportsdao.MeetingDetailBean;
import com.msr.util.SingletonClass;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author piyush
 * @Since march 06, 2013
 * @version V1.0
 */
public class MeetingReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form MeetingReportPanel
     */
    List<MeetingDetailBean> meetingList = null;
    public MeetingReportPanel(String email , List<MeetingDetailBean> meetingList) {
        this.meetingList= meetingList;
        System.out.println("meeting list size is"+meetingList.size());
        initComponents();
        int counter = 0;
        DefaultTableModel tableModel = (DefaultTableModel) detailsTable.getModel();
        Iterator<MeetingDetailBean> itr = meetingList.iterator();
        while(itr.hasNext()){
         MeetingDetailBean  meetingBean = itr.next();
          tableModel.insertRow(counter, new Object[]{});
        detailsTable.setValueAt(counter+1, counter, 0);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getDate()), counter, 1);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getTime()), counter, 2);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getRmName()), counter, 3);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getClientName()), counter, 4);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getContactPerson()), counter, 5);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getMobileNumber()), counter, 6);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getType()), counter, 7);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getComments()), counter, 8);
        detailsTable.setValueAt(SingletonClass.replaceEmptySpace(meetingBean.getCaseSummary()), counter, 9);
        counter++;
        }
       
      
//       TableColumn col1 = detailsTable.getColumnModel().getColumn(1);
//       col1.setWidth(400);
//       col1.setMaxWidth(400);
//       col1.setResizable(false);
       TableColumn col2 = detailsTable.getColumnModel().getColumn(2);
       col2.setWidth(100);
       col2.setMaxWidth(100);
       col2.setResizable(false);
       
       TableColumn col0 = detailsTable.getColumnModel().getColumn(0);
       col0.setWidth(60);
       col0.setMaxWidth(60);
       col0.setResizable(false);
        TableColumn col1 = detailsTable.getColumnModel().getColumn(1);
       col1.setMinWidth(200);
       col1.setWidth(200);
       col1.setMaxWidth(200);
//       col1.setResizable(false);
       TableColumn col3 = detailsTable.getColumnModel().getColumn(3);
       col3.setMinWidth(200);
       col3.setWidth(200);
       col3.setMaxWidth(200);
//       col3.setResizable(false);
        TableColumn col4 = detailsTable.getColumnModel().getColumn(4);
       col4.setMinWidth(200);
       col4.setWidth(200);
       col4.setMaxWidth(200);
//       col4.setResizable(false);
       TableColumn col5 = detailsTable.getColumnModel().getColumn(5);
       col5.setMinWidth(200);
       col5.setWidth(200);
       col5.setMaxWidth(200);
//       col5.setResizable(false);
       TableColumn col6 = detailsTable.getColumnModel().getColumn(6);
       col6.setMinWidth(200);
       col6.setWidth(200);
       col6.setMaxWidth(200);
//       col6.setResizable(false);
       TableColumn col7 = detailsTable.getColumnModel().getColumn(7);
       col7.setMinWidth(200);
       col7.setWidth(200);
       col7.setMaxWidth(200);
//       col7.setResizable(false);
       TableColumn col8 = detailsTable.getColumnModel().getColumn(8);
       col8.setMinWidth(200);
       col8.setWidth(200);
       col8.setMaxWidth(500);
       TableColumn col9 = detailsTable.getColumnModel().getColumn(9);
       col9.setMinWidth(200);
       col9.setWidth(200);
       col9.setMaxWidth(500);
//       TableColumn col6 = detailsTable.getColumnModel().getColumn(6);
//       col6.setWidth(400);
//       col6.setMaxWidth(400);
//       col6.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();

        JTableHeader header = detailsTable.getTableHeader();
        header.setBackground(new Color(192, 191, 200));
        //header.setPreferredSize(new Dimension(600,35));
        Font font = new Font("Serif", Font.BOLD, 14);
        header.setForeground(new Color(0, 103, 204));

        header.setFont(font);
        detailsTable.setRowHeight(35);
        detailsTable.setAutoCreateRowSorter(true);
        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "S.No.","Date","Time","RM","Company","Contact Person","Mobile","Nature Of Transaction","Discussion Points (Min describe in 50 Words)", "Case Summary"

            }
        ));
        detailsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(detailsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
